# Generated by Django 2.2.12 on 2020-12-08 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=30, verbose_name='产品名')),
                ('product_size', models.BigIntegerField(default=1001, verbose_name='产品规格')),
                ('quantity', models.BigIntegerField(default=0, verbose_name='产品数量')),
                ('price', models.BigIntegerField(default=100, verbose_name='产品单价')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
